// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\BPSK_Modulator_Demodulator\BPSK_Modulator_Baseband.v
// Created: 2022-06-14 11:10:22
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_Modulator_Baseband
// Source Path: BPSK_Modulator_Demodulator/BPSK_Modulator/BPSK Modulator Baseband
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_Modulator_Baseband
          (in0,
           out0_re,
           out0_im);


  input   signed [15:0] in0;  // int16
  output  signed [15:0] out0_re;  // sfix16_En13
  output  signed [15:0] out0_im;  // sfix16_En13


  wire bpsk_sel;
  wire signed [15:0] inphase_val0;  // sfix16_En13
  wire signed [15:0] inphase_val1;  // sfix16_En13
  wire signed [15:0] inphase;  // sfix16_En13
  wire signed [15:0] quadrature;  // sfix16_En13


  assign bpsk_sel = in0[0];



  assign inphase_val0 = 16'sb0010000000000000;



  assign inphase_val1 = 16'sb1110000000000000;



  assign inphase = (bpsk_sel == 1'b0 ? inphase_val0 :
              inphase_val1);



  assign out0_re = inphase;

  assign quadrature = 16'sb0000000000000000;



  assign out0_im = quadrature;

endmodule  // BPSK_Modulator_Baseband

