// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\BPSK_Modulator_Demodulator\BPSK_Modulator_Demodulator.v
// Created: 2022-06-14 11:10:22
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 2e-08
// Target subsystem base rate: 2e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_Modulator_Demodulator
// Source Path: BPSK_Modulator_Demodulator
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_Modulator_Demodulator
          (In1,
           Output_rsvd);


  input   signed [15:0] In1;  // int16
  output  signed [15:0] Output_rsvd;  // int16


  wire signed [15:0] BPSK_Modulator_out1_re;  // sfix16_En13
  wire signed [15:0] BPSK_Modulator_out1_im;  // sfix16_En13
  wire signed [15:0] BPSK_Demodulator_out1;  // int16


  BPSK_Modulator u_BPSK_Modulator (.In1(In1),  // int16
                                   .Output_re(BPSK_Modulator_out1_re),  // sfix16_En13
                                   .Output_im(BPSK_Modulator_out1_im)  // sfix16_En13
                                   );

  BPSK_Demodulator u_BPSK_Demodulator (.Output_re(BPSK_Modulator_out1_re),  // sfix16_En13
                                       .Output_im(BPSK_Modulator_out1_im),  // sfix16_En13
                                       .Out1(BPSK_Demodulator_out1)  // int16
                                       );

  assign Output_rsvd = BPSK_Demodulator_out1;

endmodule  // BPSK_Modulator_Demodulator

