// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\BPSK_Modulator_Demodulator\BPSK_Demodulator.v
// Created: 2022-06-14 11:10:22
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_Demodulator
// Source Path: BPSK_Modulator_Demodulator/BPSK_Demodulator
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_Demodulator
          (Output_re,
           Output_im,
           Out1);


  input   signed [15:0] Output_re;  // sfix16_En13
  input   signed [15:0] Output_im;  // sfix16_En13
  output  signed [15:0] Out1;  // int16


  wire signed [15:0] BPSK_Demodulator_Baseband_out1;  // int16


  BPSK_Demodulator_Baseband u_BPSK_Demodulator_Baseband (.in0_re(Output_re),  // sfix16_En13
                                                         .in0_im(Output_im),  // sfix16_En13
                                                         .out0(BPSK_Demodulator_Baseband_out1)  // int16
                                                         );

  assign Out1 = BPSK_Demodulator_Baseband_out1;

endmodule  // BPSK_Demodulator

