// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\BPSK_Modulator_Demodulator\BPSK_Modulator.v
// Created: 2022-06-14 11:10:22
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_Modulator
// Source Path: BPSK_Modulator_Demodulator/BPSK_Modulator
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_Modulator
          (In1,
           Output_re,
           Output_im);


  input   signed [15:0] In1;  // int16
  output  signed [15:0] Output_re;  // sfix16_En13
  output  signed [15:0] Output_im;  // sfix16_En13


  wire signed [15:0] BPSK_Modulator_Baseband_out1_re;  // sfix16_En13
  wire signed [15:0] BPSK_Modulator_Baseband_out1_im;  // sfix16_En13


  BPSK_Modulator_Baseband u_BPSK_Modulator_Baseband (.in0(In1),  // int16
                                                     .out0_re(BPSK_Modulator_Baseband_out1_re),  // sfix16_En13
                                                     .out0_im(BPSK_Modulator_Baseband_out1_im)  // sfix16_En13
                                                     );

  assign Output_re = BPSK_Modulator_Baseband_out1_re;

  assign Output_im = BPSK_Modulator_Baseband_out1_im;

endmodule  // BPSK_Modulator

