// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\BPSK_Modulator_Demodulator\BPSK_mod_demod.v
// Created: 2022-06-12 15:11:27
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_mod_demod
// Source Path: BPSK_Modulator_Demodulator/BPSK_mod_demod
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_mod_demod
          (In1,
           Output_rsvd);


  input   signed [15:0] In1;  // int16
  output  signed [15:0] Output_rsvd;  // int16


  wire signed [15:0] BPSK_Modulator_Baseband_out1_re;  // sfix16_En15
  wire signed [15:0] BPSK_Modulator_Baseband_out1_im;  // sfix16_En15
  wire signed [15:0] BPSK_Demodulator_Baseband_out1;  // int16


  BPSK_Modulator_Baseband u_BPSK_Modulator_Baseband (.in0(In1),  // int16
                                                     .out0_re(BPSK_Modulator_Baseband_out1_re),  // sfix16_En15
                                                     .out0_im(BPSK_Modulator_Baseband_out1_im)  // sfix16_En15
                                                     );

  BPSK_Demodulator_Baseband u_BPSK_Demodulator_Baseband (.in0_re(BPSK_Modulator_Baseband_out1_re),  // sfix16_En15
                                                         .in0_im(BPSK_Modulator_Baseband_out1_im),  // sfix16_En15
                                                         .out0(BPSK_Demodulator_Baseband_out1)  // int16
                                                         );

  assign Output_rsvd = BPSK_Demodulator_Baseband_out1;

endmodule  // BPSK_mod_demod

