// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\BPSK_Modulator_Demodulator\BPSK_Demodulator_Baseband.v
// Created: 2022-06-12 13:25:44
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_Demodulator_Baseband
// Source Path: BPSK_Modulator_Demodulator/BPSK Demodulator Baseband
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_Demodulator_Baseband
          (in0_re,
           in0_im,
           out0);


  input   signed [15:0] in0_re;  // int16
  input   signed [15:0] in0_im;  // int16
  output  signed [15:0] out0;  // int16


  wire inphase_lt_zero;
  wire inphase_eq_zero;
  wire quadrature_eq_zero;
  wire [2:0] decisionLUTaddr;  // ufix3
  wire [0:7] DirectLookupTable_1;  // ufix1 [8]
  wire hardDecision;  // ufix1


  assign inphase_lt_zero = in0_re < 16'sb0000000000000000;



  assign inphase_eq_zero = in0_re == 16'sb0000000000000000;



  assign quadrature_eq_zero = in0_im == 16'sb0000000000000000;



  assign decisionLUTaddr = {inphase_lt_zero, inphase_eq_zero, quadrature_eq_zero};



  assign DirectLookupTable_1[0] = 1'b0;
  assign DirectLookupTable_1[1] = 1'b0;
  assign DirectLookupTable_1[2] = 1'b1;
  assign DirectLookupTable_1[3] = 1'b0;
  assign DirectLookupTable_1[4] = 1'b1;
  assign DirectLookupTable_1[5] = 1'b1;
  assign DirectLookupTable_1[6] = 1'b1;
  assign DirectLookupTable_1[7] = 1'b0;
  assign hardDecision = DirectLookupTable_1[decisionLUTaddr];



  assign out0 = {15'b0, hardDecision};



endmodule  // BPSK_Demodulator_Baseband

