// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\BPSK_Modulator_Demodulator\BPSK_Modulator.v
// Created: 2022-06-12 13:25:44
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_Modulator
// Source Path: BPSK_Modulator_Demodulator/BPSK_Modulator
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_Modulator
          (In1,
           Output_re,
           Output_im);


  input   signed [15:0] In1;  // int16
  output  signed [15:0] Output_re;  // int16
  output  signed [15:0] Output_im;  // int16


  wire signed [15:0] BPSK_Modulator_Baseband_out1_re;  // sfix16_En15
  wire signed [15:0] BPSK_Modulator_Baseband_out1_im;  // sfix16_En15
  wire signed [15:0] Data_Type_Conversion_out1_re;  // int16
  wire signed [15:0] Data_Type_Conversion_out1_im;  // int16


  BPSK_Modulator_Baseband u_BPSK_Modulator_Baseband (.in0(In1),  // int16
                                                     .out0_re(BPSK_Modulator_Baseband_out1_re),  // sfix16_En15
                                                     .out0_im(BPSK_Modulator_Baseband_out1_im)  // sfix16_En15
                                                     );

  assign Data_Type_Conversion_out1_re = {{15{BPSK_Modulator_Baseband_out1_re[15]}}, BPSK_Modulator_Baseband_out1_re[15]};
  assign Data_Type_Conversion_out1_im = {{15{BPSK_Modulator_Baseband_out1_im[15]}}, BPSK_Modulator_Baseband_out1_im[15]};



  assign Output_re = Data_Type_Conversion_out1_re;

  assign Output_im = Data_Type_Conversion_out1_im;

endmodule  // BPSK_Modulator

